#!/bin/sh -x

errors_email=johnl
repo_url=http://svn.pdxruby.org/repos/www/trunk
dev=~/sites/dev
current_tree=$dev/current
custom_tree=$dev/custom

######################################################################

if [ $# != 2 ]; then
    echo "Usage: $0 repository path revision"
    exit 1
fi

repo=$1; shift
rev=$1; shift

######################################################################

function check_out {
    echo 'WOULD:' svn co -r$2 $1 $3
    cp -rp ~/src/projects/pdxruby.org/trunk $3
}

function config_tree {
    for file in `cd $custom_tree && find . -type f `; do
        cp $custom_tree/$file $new_tree/$file
    done
}

function initialize_logs {
    mkdir -p $new_tree/log
    for name in development test production; do
        log=$new_tree/log/$name
        touch $log
        chmod 0666 $log
    done
}

function run_tests {
    rake 2>&1 >$new_tree/log/build.log
    echo '[not exiting]'
}

######################################################################

new_tree=$dev/r$rev

check_out $repo_url $rev $new_tree

if ! config_tree; then
    echo "failed to configure tree"
    exit 1
fi

initialize_logs

if ! run_tests; then
    mail -s "Revision $rev failed tests" $errors_email < $new_tree/log/build.log
    exit 1
fi

ln -sf $new_tree $current_tree

######################################################################
